[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; シリアルモニタ設定
monitor_speed = 115200

; アップロード設定
upload_speed = 921600

; ビルドフラグ
build_flags = 
    -D LED_BUILTIN=2
    -D DEVICE_TYPE_EFFECT_STATION

; ライブラリ依存
lib_deps =
    adafruit/Adafruit NeoPixel@^1.12.0
