; 4D@HOME EffectStation ESP32 Firmware
; PlatformIO Project Configuration

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps = 
    adafruit/Adafruit NeoPixel@^1.12.0

build_flags = 
    -D CONFIG_BT_NIMBLE_ENABLED=0
    -D CONFIG_BTDM_CTRL_MODE_BLE_ONLY=y
